add gfni support
pqov/pqov pull request #30
Opened 2024-08-23 12:37 UTC by devillegna

add gfni support. This code use only half of clock cycles for generating keys and signing.

2025-01-03 07:50 UTC, mkannwischer requested changes
Unfortunately, I am getting an `Illegal Instruction` error when I run this on my x86. 
It errors on a `vmovdqa64`.  My CPU (i7-1360P) does support `gfni`, but it does not support `avx512`. Is is possible to implement this without the `avx512vl` and `avx512bw` features?

2025-01-05 01:19 UTC, mkannwischer commented
Thanks @devillegna. Rebased this on top of #37 and will run some more tests and benchmarks now.

2025-01-05 14:12 UTC, devillegna commented
The untouched Is parameter keeps unchanged in this building setting.  
Benchmark on AMD EPYC 9754 128-Core Processor:  

Ip-Classic (gfni)
```
OV(256,112,44)-classic
sk size: 237896
pk size: 278432
signature overhead: 128

===========  benchmark crypto_sign_keypair()  ================

benchmark:  crypto_sign_keypair(): 6772296 (cycles, avg. of 50): 6210292 6120022 6175710 6129473 6188490 6178725

===========  benchmark crypto_sign() and crypto_sign_open()  ================

benchmark:  crypto_sign(): 256786 (cycles, avg. of 500): 254475 244283 242820 246690 245048 295920

benchmark:  crypto_sign_open(): 413017 (cycles, avg. of 500): 392400 399645 398295 405832 405360 402615
```

Ip-Classic (avx2)
```
OV(256,112,44)-classic
sk size: 237896
pk size: 278432
signature overhead: 128

===========  benchmark crypto_sign_keypair()  ================

benchmark:  crypto_sign_keypair(): 12233522 (cycles, avg. of 50): 11611283 11571322 11656710 11601293 11619720 11548890

===========  benchmark crypto_sign() and crypto_sign_open()  ================

benchmark:  crypto_sign(): 394132 (cycles, avg. of 500): 393233 380002 382455 379732 382140 434542

benchmark:  crypto_sign_open(): 408116 (cycles, avg. of 500): 400905 393413 455558 401242 394583 404820
```

Is-Classic (gfni)
```
OV(16,160,64)-classic
sk size: 348704
pk size: 412160
signature overhead: 96

===========  benchmark crypto_sign_keypair()  ================

benchmark:  crypto_sign_keypair(): 20125576 (cycles, avg. of 50): 19642905 20569815 19734435 19418895 19397363 19463715

===========  benchmark crypto_sign() and crypto_sign_open()  ================

benchmark:  crypto_sign(): 461540 (cycles, avg. of 500): 427050 420907 421110 478192 424417 825547

benchmark:  crypto_sign_open(): 495739 (cycles, avg. of 500): 485505 544658 484380 470025 486832 478620
```

Is-Classic (avx2)
```
OV(16,160,64)-classic
sk size: 348704
pk size: 412160
signature overhead: 96

===========  benchmark crypto_sign_keypair()  ================

benchmark:  crypto_sign_keypair(): 20060529 (cycles, avg. of 50): 19409220 19328760 19817798 19437435 19272847 19462905

===========  benchmark crypto_sign() and crypto_sign_open()  ================

benchmark:  crypto_sign(): 461836 (cycles, avg. of 500): 828878 423698 419917 422640 491693 424058

benchmark:  crypto_sign_open(): 495314 (cycles, avg. of 500): 502470 497700 477630 465638 470790 461812
```

2025-01-06 05:44 UTC, mkannwischer approved these changes
Thanks! 
I confirm that now the GF16 performance is unaffected by this PR. 
LGTM.

2025-01-06 06:05 UTC, merged